config/routes.rb
OfficeAutomationProject::Engine.routes.draw do
  mount OfficeAutomationEmployee::Engine => '/employee'
  resources :companies do
    resources :clients
    resources :projects do
       resources :contact_persons, only: ['destroy', 'show']
    end
  end
end

app/models/office_automation_project/ability.rb
module OfficeAutomationProject
  class Ability < OfficeAutomationEmployee::Ability

    def initialize(current_user)
      if current_user.role? OfficeAutomationEmployee::Role::ADMIN
        can [:create], Project

        can [:update, :edit, :index, :show], Project, company: current_user.company


        can [:create], Client
        can [:update, :edit, :index, :show], Client, company: current_user.company

      else

        can [:show, :index], Project do |project|
          p current_user.project_list
          current_user.project_list.collect(&:id).include? (project.id)
        end

        if current_user.is_manager?
          can [:edit, :update], Project do |project|
            project.managers.collect(&:user_id).include? (current_user.id)
          end
        end
      end

      # Define abilities for the passed in user here. For example:
      #
      #   user ||= User.new # guest user (not logged in)
      #   if user.admin?
      #     can :manage, :all
      #   else
      #     can :read, :all
      #   end
      #
      # The first argument to `can` is the action you are giving the user 
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      #
      # The second argument is the resource the user can perform the action on. 
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      #
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #
      #   can :update, Article, :published => true
      #
      # See the wiki for details:
      # https://github.com/ryanb/cancan/wiki/Defining-Abilities
      super
    end
  end
end

app/models/office_automation_project/client.rb
module OfficeAutomationProject
  class Client
    include Mongoid::Document

    #Fields
    field :name
    field :currency
    field :primary_email_id
    field :secondary_email_id
    field :phone_no
    field :address
    field :city
    field :state
    field :country
    field :pincode, type: Integer

    #Validations
    validates :name, :primary_email_id, :secondary_email_id, :phone_no, :address, :city, :state, :country, :pincode, :currency, presence: true
    validates :name, :primary_email_id, :secondary_email_id, :phone_no, uniqueness: {scope: :company}
    validates :pincode, numericality: true
    validates :primary_email_id, :secondary_email_id, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
    validates :phone_no, format: {with: /\+(?:[0-9]??){6,14}[0-9]/}

    #Relationships
    has_many :projects, class_name: 'OfficeAutomationProject::Project'
    belongs_to :company, class_name: 'OfficeAutomationEmployee::Company'
    
    def full_address 
      "#{self.address} \n #{self.city.humanize}, #{self.state.humanize} \n #{self.country}, #{self.pincode}"
    end
  end
end

app/models/office_automation_project/contact_person.rb
module OfficeAutomationProject
  class ContactPerson
    include Mongoid::Document

    #Fields
    field :name
    field :primary_email_id
    field :secondary_email_id
    field :phone_no
    field :address
    field :skype_id
    field :linkedin_id
    field :twitter_id

    #Validations
    validates :name, :primary_email_id, :phone_no, presence: true
    validates :primary_email_id, :secondary_email_id, :phone_no, :skype_id, :linkedin_id, :twitter_id, {uniqueness: true, allow_blank: true}
    validates :primary_email_id, :secondary_email_id, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
    validates :phone_no, format: {with: /\+(?:[0-9]??){6,14}[0-9]/}

    #Relationships
    embedded_in :project, class_name: 'OfficeAutomationProject::Project'

  end
end

app/models/office_automation_project/project.rb
module OfficeAutomationProject
  class Project
    include Mongoid::Document
    include AASM

    #Fields
    field :name
    field :description
    field :start_date, type: Date
    field :end_date, type: Date
    field :codeclimate_url
    field :status

    #Validation
    validates :name, :start_date, :client_id, presence: true
    validates :name, uniqueness: {scope: :company}
    validate :end_date_validation

    #Relationship
    embeds_many :attachments, class_name: 'OfficeAutomationEmployee::Attachment'
    belongs_to :company, class_name: 'OfficeAutomationEmployee::Company'

    embeds_many :contact_persons, class_name: 'OfficeAutomationProject::ContactPerson'
    has_many :project_members, class_name: 'OfficeAutomationProject::ProjectMember', dependent: :destroy
    belongs_to :client, class_name: 'OfficeAutomationProject::Client'

    accepts_nested_attributes_for :project_members
    accepts_nested_attributes_for :contact_persons


    before_save :has_unique_user

    # whiny_transition set to false for true/false response instead of exceptions
    # Default field is aasm_state we can specify field using column
    aasm column: 'status', whiny_transitions: false do
      state :pending, initial: true#, before_enter: :send_email To all admin of company
      state :active
      state :deactive
      state :completed
      state :maintainance
      state :close

      event :activate, after: :state_change do
        transitions from: [:pending, :deactive], to: :active
      end

      event :deactivate do
        transitions from: :active, to: :deactive
      end

      event :complete do
        transitions from: [:active, :deactive], to: :completed#, guard: :is_admin
      end

      event :maintain do
        transitions from: [:completed], to: :maintainance
      end

      event :close do
        transitions from: [:active, :deactive, :completed, :maintainance], to: :close
      end

    end

    def state_change
      puts "State of project has been changed"
      puts "From: #{aasm.from_state} to #{aasm.to_state} "
    end


    def managers
      self.project_members.where(is_manager: true).all.to_a
    end

    private
    def end_date_validation
      self.errors[:end_date] << "Invalid" if (end_date? and end_date < start_date)
    end

    def has_unique_user
      error_count = 0
      pro_mem=self.project_members.collect(&:user_id)
      self.project_members.each do |project_member| 
        count = 0
        pro_mem.each do |p|
          count = count+1 if (project_member.user_id).eql?(p)
        end
        if count > 1
          error_count = error_count + 1
          project_member.errors[:user_id] << "is duplicated on same form"
        end
      end
      false if (error_count > 0)
    end
  end

end

app/models/office_automation_project/project_member.rb
module OfficeAutomationProject
  class ProjectMember
    include Mongoid::Document
    
    field :is_manager, type: Mongoid::Boolean
    
    belongs_to :user, class_name: 'OfficeAutomationEmployee::User'
    belongs_to :project, class_name: 'OfficeAutomationProject::Project'

    validates :user_id, uniqueness: {scope: :project}
    validates :user_id, :project_id, presence: true

  end
end

app/controllers/office_automation_project/application_controller.rb
module OfficeAutomationProject
  class ApplicationController < ActionController::Base
    before_filter :authenticate_user!

    rescue_from CanCan::AccessDenied do |exception|
      flash[:danger] = "You are not allowed to perform this action."
      redirect_to main_app.root_path
    end
  end
end

app/controllers/office_automation_project/clients_controller.rb
require_dependency "office_automation_project/application_controller"

module OfficeAutomationProject
  class ClientsController < ApplicationController
    load_and_authorize_resource

    before_action :load_client, only: [:edit, :show, :update]
    def new
      @client = Client.new
    end

    def create
      @client = Client.new(client_params)
      @client.company = current_user.company
      if @client.save
        flash[:success] = "Congratulations!! You have successfully added client"
        redirect_to office_automation_project.new_company_client_path
      else
        flash[:danger] = "Please fill the mandatory fields"
        render :new
      end
    end

    def index
      @clients = current_user.company.clients
    end

    def edit
    end

    def update
      if @client.update_attributes client_params
        flash[:success] = "Congratulations!! You have successfully updated client"
        redirect_to office_automation_project.edit_company_client_path
      else
        flash[:danger] = "Please fill details accordingly"
        render :edit
      end

    end

    def show
    end

    def load_client
      @client = Client.find[params[:id])
    end

    private

    def client_params
      params[:client].permit(:name, :currency, :primary_email_id, :secondary_email_id, :phone_no, :address, :city, :state, :country, :pincode)
    end

  end
end

app/controllers/office_automation_project/contact_persons_controller.rb
require_dependency "office_automation_project/application_controller"

module OfficeAutomationProject
  class ContactPersonsController < ApplicationController
    def destroy
      @project = Project.find(params[:project_id])
      @contact_person = @project.contact_persons.find(params[:id])
      if @contact_person.destroy
        flash[:success] = 'Contact person deleted successfully!!'
      else
        flash[:danger] = 'Unable Delete contact person!!'
      end
      respond_to do |format|
        format.js
      end
    end

    def show
      @project = Project.find(params[:project_id])
      @contact_person = @project.contact_persons.find(params[:id])
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/office_automation_project/projects_controller.rb
require_dependency "office_automation_project/application_controller"

module OfficeAutomationProject
  class ProjectsController < ApplicationController

    load_and_authorize_resource
    before_action :load_project, only: [:edit, :show, :update]

    def index
      @projects = (current_user.role? OfficeAutomationEmployee::Role::ADMIN) ? current_user.company.projects.all : current_user.project_list
    end

    def show
    end

    def edit
      @users = current_user.company.users.where(status: 'Active')
      @clients = current_user.company.clients
      @project.contact_persons.build
      @project.project_members.build
    end

    def update
      if @project.update_attributes project_params
        flash[:success] = "Congratulations!! You have successfully updated a project"
        redirect_to office_automation_project.edit_company_project_path(@current_user.company, @project)
      else
        @users = current_user.company.users.where(status: 'Active')
        flash[:danger] = "Please fill the fields accordingly.."
        render :edit
      end
    end

    def new
      @project = Project.new
      @project.contact_persons.build
      @company =  OfficeAutomationProject::Project.find(params[:company_id])
      @project_members = @project.project_members.build
      @users = current_user.company.users.where(status: 'Active')
    end

    def create
      @project = Project.new(project_params)
      @project.company = current_user.company

      if @project.valid? and @project.save
        flash[:success] = "Congratulations!! You have successfully created a project"
        redirect_to office_automation_project.new_company_project_path 
      else
        @users = current_user.company.users.where(status: 'Active')
        flash[:danger] = "Please fill the mandatory fields"
        render :new
      end
    end

    def load_project
      @project = Project.find(params[:id])
    end
    private

    def project_params
      params[:project][:contact_persons_attributes].keep_if{|k,v| v[:_destroy] == 'false' if v.has_key?(:_destroy) } if params[:project].include?(:contact_persons_attributes)

      params[:project][:project_members_attributes].keep_if{|k,v| v[:_destroy] == 'false' if v.has_key?(:_destroy) } if params[:project].include?(:project_members_attributes)

      params.require(:project).permit(:name, :status, :description, :start_date, :end_date, :codeclimate_url, :client_id, project_members_attributes: [:is_manager, :id, :user_id], contact_persons_attributes: [:name, :primary_email_id, :secondary_email_id, :phone_no, :address, :skype_id, :linkedin_id, :twitter_id, :id])
    end
  end

end

app/helpers/office_automation_project/application_helper.rb
module OfficeAutomationProject
  module ApplicationHelper
  end
end

app/views/office_automation_project/projects/_client_details.html.haml
.row
  .col-md-6
    .form-group
      %label Name:
      = client.name
      
  .col-md-6
    .form-group
      %label Currency:
      = client.currency
.row
  .col-md-6
    .form-group
      %label Primary Email ID:
      = client.primary_email_id
  .col-md-6
    .form-group
      %label Secondary Email ID:
      = client.secondary_email_id
.row
  .col-md-6
    .form-group
      %label Address:
      = simple_format client.full_address
  .col-md-6
    .form-group
      %label Phone Number:
      = client.phone_no

app/views/office_automation_project/projects/_contact_person.html.haml
#new_contact_person

  = f.fields_for :contact_persons do |contact_person|
    .form-group{id: "#{contact_person.object._id}"}
      .row
        .col-md-4
          .form-group
            = contact_person.input :name, required: false, label: '* Name', input_html: {class: "form-control", placeholder: 'Enter Name'}
        .col-md-4
          .form-group
            = contact_person.input :primary_email_id, required: false,label: '* Primary Email', input_html: {class: "form-control", placeholder: 'example@domain.com'}
        .col-md-4
          .form-group
            = contact_person.input :secondary_email_id,label: '* Secondary Email', input_html: {class: "form-control", placeholder: 'example@domain.com'}
      .row
        .col-md-4
          .form-group
            = contact_person.input :phone_no,as: :tel, required: false, label: '* Phone Number',input_html: {class: "form-control", placeholder: '+91 1234567890'}
        .col-md-4
          .form-group
            = contact_person.input :twitter_id, input_html: {class: "form-control", placeholder: 'Enter Twitter Id'}
        .col-md-4
          .form-group
            = contact_person.input :skype_id, input_html: {class: "form-control", placeholder: 'Enter Skype Id'}
      .row
        .col-md-4
          .form-group
            = contact_person.input :linkedin_id, input_html: {class: "form-control", placeholder: 'Enter Linkedin Id'}
        .col-md-4
          .form-group
            = contact_person.input :address,as: :text, input_html: {class: "form-control", placeholder: 'Enter Address'}
        .col-md-4
          %br
          .form-group
            - if contact_person.object.new_record?
              = contact_person.link_to_remove "Remove", class: "btn btn-primary"
            - else
              = contact_person.hidden_field :_destroy, value: false
              = link_to "Delete",company_project_contact_person_path(current_user.company, f.object.id, contact_person.object.id), remote: true, data: {confirm: 'Are you sure?', disable_with: "Deleting.."} , method: :delete,class: "btn btn-danger"




.row
  .col-md-8
  .col-md-2
  = f.link_to_add "Add More", :contact_persons, class: "btn btn-primary", data: { target: "#new_contact_person" }

app/views/office_automation_project/projects/_contact_persons_details.html.haml
.form-group
  .row
    .col-md-6
      .form-group
        %label Name:
        = contact_person.name
    .col-md-6
      .form-group
        %label Primary Email ID:
        = contact_person.primary_email_id
  .row
    .col-md-6
      .form-group
        %label Secondary Email ID:
        = contact_person.secondary_email_id
    .col-md-6
      .form-group
        %label Phone Number:
        = contact_person.phone_no
  .row
    .col-md-6
      .form-group
        %label Address: 
        = contact_person.address
    .col-md-6
      .form-group
        %label Skype ID:
        = contact_person.skype_id
  .row
    .col-md-6
      %label Linkedin ID:
      = contact_person.linkedin_id
    .col-md-6
      %label Twitter ID:
      = contact_person.twitter_id

app/views/office_automation_project/projects/_project.html.haml
.row
  .col-md-4
    .form-group
      = f.input :name, autofocus: true, input_html: { class: "form-control", maxlength: 30, placeholder: "Enter project name here", required: true }
  .col-md-4
    .form-group
      = f.input :status,collection: ["Pending","Active","Deactive", "Completed", "Maintainance", "Close"], input_html: {class: "form-control", value: (f.object.status ? f.object.status : 'pending')}
  .col-md-4
    .form-group
      = f.input :description, as: :text, input_html: {class: "form-control", maxlength: 150, placeholder: "Description"}
              
.row
  .col-md-4
    %label *Start Date
    .form-group
      .customdatepicker.input-group.date
        = f.input :start_date, label: false, input_html: {class: "form-control", readonly: true,  value: f.object.start_date.try(:strftime, '%d-%m-%Y')}
        %span.input-group-addon.glyphicon.glyphicon-calendar

  .col-md-4
    %label End Date
    .form-group
      .customdatepicker.input-group.date
        = f.input :end_date, label: false, input_html: {class: "form-control", readonly: true,  value: f.object.start_date.try(:strftime, '%d-%m-%Y')}
        %span.input-group-addon.glyphicon.glyphicon-calendar

  .col-md-4
    .form-group
      = f.input :codeclimate_url, as: :url, input_html: {class: "form-control", placeholder: "http://codeclimate.com"}


  .col-md-4
    .form-group
      = f.association :client, collection: current_user.company.clients, input_html: {class: "form-control"}

.form-group
  .well.well-sm
    %strong Project Members
  = render partial: "office_automation_project/projects/project_member", locals: {f: f}

.form-group
  .well.well-sm
    %strong Contact Persons
  = render partial: "office_automation_project/projects/contact_person", locals: {f: f}

app/views/office_automation_project/projects/_project_details.html.haml
.row
  .col-md-6
    .form-group
      %label Name:
      = project.name
  .col-md-6
    .form-group
      %label Start Date:
      = project.start_date.try(:strftime, '%d-%m-%y')
.row
  .col-md-6
    .form-group
      %label End Date:
      = project.end_date ? project.end_date.try(:strftime, '%d-%m-%y') : "Not entered"
  .col-md-6
    .form-group
      %label Description:
      = project.description ? project.description : "Not entered"
.row
  .col-md-6
    .form-group
      %label Status:
      = project.status
  .col-md-6
    .form-group
      %label Codeclimate:
      = project.codeclimate_url ? project.codeclimate_url : "Not entered"

app/views/office_automation_project/projects/_project_member.html.haml
#new_project_member
  = f.fields_for :project_members do |project_member|
    .form-group
      .row
        .col-md-4
          .form-group

            = project_member.association :user, collection: @users.collect{|u| [u.email, u.id.to_s]}, label: '* User', required: false,input_html: {class: "form-control userdata"}

        .col-md-4
          .form-group
            = project_member.input :is_manager, as: :boolean,required: false, input_html: {class: "form-control"}
        .col-md-4
          %br
          .form-group
            - if project_member.object.new_record?
              = project_member.link_to_remove "Remove", class: "btn btn-primary"
            - else
              = project_member.hidden_field :_destroy, value: false


.row
  .col-md-8
  .col-md-2
    = f.link_to_add "Add More", :project_members, class: "btn btn-primary", data: { target: "#new_project_member" }

:javascript
  var users = #{@users.to_json}

app/views/office_automation_project/projects/edit.html.haml
.row
  .col-md-2
  .col-md-8
    .custom-alert
    = render 'office_automation_employee/shared/flash'
    .panel.panel-default
      .panel-heading
        %strong= @project.name + " project's profile"
      .panel-body
        .container-fluid
          = simple_nested_form_for(@project, url: office_automation_project.company_project_path, input_html: { role: :form } ) do |f|
            = render partial: 'office_automation_project/projects/project', locals: {f: f}
            .form-group= f.submit class: "btn btn-primary"

app/views/office_automation_project/projects/index.html.haml
.row
  .col-md-12
    = render "office_automation_employee/shared/flash"
    .panel.panel-default
      .panel-heading
        %strong Projects
      .panel-body
        .container-fluid
          .col-md-12
            - if @projects.count > 0
              %table.table.table-hover
                %thead
                  %tr
                    %th Name
                    %th Client
                    %th Status
                    %th Codeclimate
                    %th= "Edit" if can?(:edit, OfficeAutomationProject::Project)
                %tbody.rowlink{ "data-link" => "row" }
                  - @projects.each_with_index do |project, index|
                    %tr
                      %td= link_to project.name, office_automation_project.company_project_path(project.company, project)
                      %td= project.client.name
                      %td= project.status
                      %td= project.codeclimate_url
                      %td.rowlink-skip= link_to(content_tag(:span, "", class: "glyphicon glyphicon-edit"), office_automation_project.edit_company_project_path(project.company, project), class: "btn btn-default") if can?(:edit,project)
            - else
              .form-group
                %center
                  %strong You are not assigned to any of the project!!

app/views/office_automation_project/projects/new.html.haml
.row
  .col-md-2
  .col-md-8
    = render "office_automation_employee/shared/flash"
    .panel.panel-default
      .panel-heading
        %strong Create new project

      .panel-body
        .container-fluid
          = simple_nested_form_for(@project, url: office_automation_project.company_projects_path, input_html: { role: :form } ) do |f|
            .form-group
              = render partial: "office_automation_project/projects/project", locals: {f: f}

            .form-group= f.submit class: "btn btn-primary"

app/views/office_automation_project/projects/show.html.haml
.row
  .col-md-2
  .col-md-8
    .panel.panel-default
      .panel-heading
        %strong= @project.name
      .panel-body
        .container-fluid
          = render partial: "office_automation_project/projects/project_details", locals: { project: @project }
          - if can?(:edit, @project)
            .well.well-sm
              %strong= "Client"
            = render partial: "office_automation_project/projects/client_details", locals:{client: @project.client}
            
            - if @project.contact_persons.count > 0
              .well.well-sm
                %strong= "Contact Person"
              %table.table.table-hover 
                %thead
                  %tr
                  %th Name
                  %th Primary Email-Id
                  %th Phone Number
                  %th Skype Id
                  %th More
                %tbody
                  - @project.contact_persons.each_with_index do |contact_person, index|
                    %tr
                      %td= contact_person.name
                      %td= contact_person.primary_email_id
                      %td= contact_person.phone_no
                      %td= contact_person.skype_id

                      %td.rowlink-skip= link_to(content_tag(:span, "More", class: "btn btn-primary"), office_automation_project.company_project_contact_person_path(@project.company, @project, contact_person), data: {toggle: "modal"}, remote: true) if can?(:edit,@project)
          - if @project.project_members.count > 0
            .well.well-sm
              %strong= "Project Member"
            %table.table.table-hover
              %thead
                %tr
                %th #
                %th Name
                %th Email-Id
                %th Manager
              %tbody
                - @project.project_members.each_with_index do |project_member, index|
                  %tr
                    %td= index + 1
                    %td= project_member.user.fullname
                    %td= project_member.user.email
                    %td= (project_member.is_manager ? "YES" : "NO") 
          - if can?(:edit, @project)
            %p{ align: :right }
              = link_to "Edit", office_automation_project.edit_company_project_path(@project.company, @project) ,class: "btn btn-primary" 